;; Custom-set-variables separated from init.el
;; This file is automatically generated by Emacs
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(ac-math auctex badwolf-theme centaur-tabs citar company
	     company-auctex company-math consult helm-descbinds
	     lsp-java lsp-ltex lsp-mode lsp-python-ms lsp-ui magit
	     marginalia multiple-cursors orderless popup swiper tabbar
	     undo-tree use-package vertico web-mode which-key
	     yasnippet-snippets))
 '(tabbar-separator '(0.5))
 '(warning-suppress-log-types '((comp)))
 '(warning-suppress-types
   '((auto-save) (auto-save) (auto-save) (auto-save) (auto-save)))
 '(xref-after-return-hook nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
